/**
 * Test selector constants for Playwright E2E tests
 *
 * Centralized location for all data-testid values to ensure consistency
 * and make test maintenance easier.
 */

export const TestSelectors = {
  // Layout
  APP_ROOT: "app-root",
  ADMIN_LAYOUT: "admin-layout",
  ADMIN_AUTH_LOADING: "admin-auth-loading",
  ADMIN_HEADER_BAR: "admin-header-bar",
  ADMIN_NAV_LOGO: "admin-nav-logo",
  AUTH_LAYOUT: "auth-layout",

  // Header
  ADMIN_HEADER: "admin-header",
  HEADER_LOGO: "header-logo",
  HEADER_USER_MENU: "header-user-menu",
  HEADER_USER_MENU_BUTTON: "header-user-menu-button",
  HEADER_COLOR_SCHEME_TOGGLE: "header-color-scheme-toggle",
  HEADER_MOBILE_MENU_TOGGLE: "header-mobile-menu-toggle",
  HEADER_ACCOUNT_LINK: "header-account-link",

  // Navigation
  ADMIN_NAV: "admin-nav",
  NAV_ITEM: (slug: string) => `nav-item--${slug}`,
  NAV_SEARCH_INPUT: "nav-search-input",
  SIDEBAR_LOGO_MARK: "sidebar-logo-mark",
  SIDEBAR_MOBILE_MENU_TOGGLE: "sidebar-mobile-menu-toggle",

  // Common UI Elements
  BUTTON: {
    ACCOUNT_CHANGE_PASSWORD: "button--account-change-password",
    ACCOUNT_EDIT: "button--account-edit",
    ACCOUNT_REFRESH: "button--account-refresh",
    BAN_USER: "button--ban-user",
    CANCEL: "button--cancel",
    CHANGE_PASSWORD: "button--change-password",
    CLOSE: "button--close",
    CREATE_ANNOUNCEMENT: "button--create-announcement",
    CREATE_PLAN: "button--create-plan",
    DELETE: "button--delete",
    GO_HOME: "button--go-home",
    GRANT_PLATFORM_ADMIN: "button--grant-platform-admin",
    PUBLISH: "button--publish",
    RETRY: "button--retry",
    REVOKE_INVITATION: "button--revoke-invitation",
    REVOKE_PLATFORM_ADMIN: "button--revoke-platform-admin",
    SAVE_CHANGES: "button--save-changes",
    SEND_INVITATION: "button--send-invitation",
    SET_PASSWORD: "button--set-password",
    SIGN_OUT: "button--sign-out",
    TRY_AGAIN: "button--try-again",
    UNBAN_USER: "button--unban-user",
    UNLOCK_USER: "button--unlock-user",
    ANNOUNCEMENT_DELETE: (id: string) => `button-announcement-delete--${id}`,
    ANNOUNCEMENT_EDIT: (id: string) => `button-announcement-edit--${id}`,
    ANNOUNCEMENTS_CLEAR_FILTERS: "button-announcements-clear-filters",
    ANNOUNCEMENTS_CREATE: "button-announcements-create",
    ANNOUNCEMENTS_REFRESH: "button-announcements-refresh",
    AUDIT_DETAIL_CLOSE: "button-audit-detail-close",
    AUDIT_RECORD_VIEW: (id: string) => `button-audit-record-view--${id}`,
    AUDIT_REFRESH: "button-audit-refresh",
    AUDIT_TENANT_KEY_CLEAR: "button-audit-tenant-key-clear",
    BILLING_CREATE: "button-billing-create",
    BILLING_CREATE_CANCEL: "button-billing-create-cancel",
    BILLING_CREATE_SUBMIT: "button-billing-create-submit",
    BILLING_DELETE: "button-billing-delete",
    BILLING_DELETE_CANCEL: "button-billing-delete-cancel",
    BILLING_DELETE_CONFIRM: "button-billing-delete-confirm",
    BILLING_OPEN_PORTAL: "button-billing-open-portal",
    BILLING_SAVE: "button-billing-save",
    EDIT_AUTHORITIES_CANCEL: "button-edit-authorities-cancel",
    EDIT_AUTHORITIES_SAVE: "button-edit-authorities-save",
    INVITATION_MANAGE: (invitationId: string) => `button-invitation-manage--${invitationId}`,
    INVITATIONS_CLEAR_FILTERS: "button-invitations-clear-filters",
    INVITATIONS_PROPOSE: "button-invitations-propose",
    INVITATIONS_REFRESH: "button-invitations-refresh",
    INVITATIONS_SEARCH_CLEAR: "button-invitations-search-clear",
    INVITATIONS_TENANT_KEY_CLEAR: "button-invitations-tenant-key-clear",
    MEMBER_EDIT_AUTHORITIES: (userId: string) => `button-member-edit-authorities--${userId}`,
    MEMBERS_REFRESH: "button-members-refresh",
    MEMBERS_SEARCH_CLEAR: "button-members-search-clear",
    ORG_BILLING: (tenantKey: string) => `button-org-billing--${tenantKey}`,
    ORG_DETAIL_EDIT: "button-org-detail-edit",
    ORG_DETAIL_ERROR_RETRY: "button-org-detail-error-retry",
    ORG_DETAIL_REFRESH: "button-org-detail-refresh",
    ORG_EDIT: (tenantKey: string) => `button-org-edit--${tenantKey}`,
    ORG_REFUND_VIEW: (id: string) => `button-org-refund-view--${id}`,
    ORG_SUB_VIEW: (id: string) => `button-org-sub-view--${id}`,
    ORG_SUBS_SEARCH_CLEAR: "button-org-subs-search-clear",
    ORG_VIEW: (tenantKey: string) => `button-org-view--${tenantKey}`,
    ORGS_CLEAR_FILTERS: "button-orgs-clear-filters",
    ORGS_REFRESH: "button-orgs-refresh",
    ORGS_SEARCH_CLEAR: "button-orgs-search-clear",
    PLATFORM_AUTHORITY_REFRESH: "button-platform-authority-refresh",
    REFUND_DETAIL_ERROR_RETRY: "button-refund-detail-error-retry",
    REFUND_VIEW: (id: string) => `button-refund-view--${id}`,
    REFUNDS_TENANT_KEY_CLEAR: "button-refunds-tenant-key-clear",
    SUB_DELETE: "button-sub-delete",
    SUB_DELETE_CANCEL: "button-sub-delete-cancel",
    SUB_DELETE_CONFIRM: "button-sub-delete-confirm",
    SUB_DETAIL_ERROR_RETRY: "button-sub-detail-error-retry",
    SUB_MENU: (subscriptionId: string) => `button-sub-menu--${subscriptionId}`,
    SUB_RESET: "button-sub-reset",
    SUB_SAVE: "button-sub-save",
    SUB_VIEW: (subscriptionId: string) => `button-sub-view--${subscriptionId}`,
    SUBS_CLEAR_FILTERS: "button-subs-clear-filters",
    SUBS_REFRESH: "button-subs-refresh",
    SUBS_SEARCH_CLEAR: "button-subs-search-clear",
    TRANSLATION_ADD_LOCALE: "button-translation-add-locale",
    TRANSLATION_REMOVE: (index: number) => `button-translation-remove--${index}`,
    USER_DETAIL_EDIT: "button-user-detail-edit",
    USER_DETAIL_ERROR_RETRY: "button-user-detail-error-retry",
    USER_DETAIL_REFRESH: "button-user-detail-refresh",
    USER_DETAIL_SET_PASSWORD: "button-user-detail-set-password",
    USER_DETAIL_UNLOCK: "button-user-detail-unlock",
    USER_MENU: (userId: string) => `button-user-menu--${userId}`,
    USER_VIEW: (userId: string) => `button-user-view--${userId}`,
    USERS_CLEAR_FILTERS: "button-users-clear-filters",
    USERS_REFRESH: "button-users-refresh",
    USERS_SEARCH_CLEAR: "button-users-search-clear",
  },
  LINK: (name: string) => `link--${name}`,
  INPUT: {
    ACTIVE: "input--active",
    AUTHORITY: "input--authority",
    BAN_REASON: "input--ban-reason",
    BILLING_PERIOD: "input--billing-period",
    CONFIRM_PASSWORD: "input--confirm-password",
    CURRENCY: "input--currency",
    CURRENT_PASSWORD: "input--current-password",
    DISPLAY_NAME: "input--display-name",
    EMAIL: "input--email",
    FEATURE_SET: "input--feature-set",
    FIRST_NAME: "input--first-name",
    LANGUAGE: "input--language",
    LAST_NAME: "input--last-name",
    NEW_PASSWORD: "input--new-password",
    ORGANIZATION_NAME: "input--organization-name",
    PLAN_CODE: "input--plan-code",
    PRICE_MINOR: "input--price-minor",
    SCOPE: "input--scope",
    STATUS: "input--status",
    TENANT_KEY: "input--tenant-key",
    TYPE: "input--type",
    AUDIT_TENANT_KEY_FILTER: "input-audit-tenant-key-filter",
    INVITATIONS_SEARCH: "input-invitations-search",
    INVITATIONS_TENANT_KEY_FILTER: "input-invitations-tenant-key-filter",
    MEMBERS_SEARCH: "input-members-search",
    ORG_SUBS_SEARCH: "input-org-subs-search",
    ORGS_SEARCH: "input-orgs-search",
    REFUND_AMOUNT: "input-refund-amount",
    REFUND_EXTERNAL_CUSTOMER_ID: "input-refund-external-customer-id",
    REFUND_EXTERNAL_PAYMENT_ID: "input-refund-external-payment-id",
    REFUND_EXTERNAL_REFUND_ID: "input-refund-external-refund-id",
    REFUND_ID: "input-refund-id",
    REFUND_OCCURRED_AT: "input-refund-occurred-at",
    REFUND_STATUS: "input-refund-status",
    REFUND_TENANT_KEY: "input-refund-tenant-key",
    REFUNDS_TENANT_KEY_FILTER: "input-refunds-tenant-key-filter",
    SUB_CANCEL_AT_PERIOD_END: "input-sub-cancel-at-period-end",
    SUB_EXTERNAL_ID: "input-sub-external-id",
    SUB_ID: "input-sub-id",
    SUB_PERIOD_END: "input-sub-period-end",
    SUB_PLAN_ID: "input-sub-plan-id",
    SUB_QUANTITY: "input-sub-quantity",
    SUB_STATUS: "input-sub-status",
    SUB_TENANT_KEY: "input-sub-tenant-key",
    SUB_TRIAL_END: "input-sub-trial-end",
    SUB_TRIAL_START: "input-sub-trial-start",
    SUBS_SEARCH: "input-subs-search",
    TRANSLATION_MESSAGE: (index: number) => `input-translation-message--${index}`,
    TRANSLATION_TITLE: (index: number) => `input-translation-title--${index}`,
    USERS_SEARCH: "input-users-search",
  },
  FORM: {
    SUB_DETAIL: "form-sub-detail",
  },
  MODAL: {
    BAN_USER: "modal--ban-user",
    CHANGE_ADMIN_PASSWORD: "modal--change-admin-password",
    CREATE_ANNOUNCEMENT: "modal--create-announcement",
    CREATE_PLAN: "modal--create-plan",
    DELETE_ANNOUNCEMENT: "modal--delete-announcement",
    EDIT_ACCOUNT: "modal--edit-account",
    EDIT_ANNOUNCEMENT: "modal--edit-announcement",
    EDIT_INVITATION: "modal--edit-invitation",
    EDIT_TENANT: "modal--edit-tenant",
    EDIT_USER: "modal--edit-user",
    PROPOSE_INVITATION: "modal--propose-invitation",
    SET_PASSWORD: "modal--set-password",
  },
  ALERT: {
    SESSION_TIMEOUT: "alert--session-timeout",
    ACCESS_FORBIDDEN: "alert--access-forbidden",
    SIGN_IN_ERROR: "sign-in-error-alert",
  },
  LOADING_OVERLAY: "loading-overlay",
  ERROR_BOUNDARY: "error-boundary",
  LOCALE_SWITCHER: "locale-switcher",

  // Pages
  PAGE: (name: string) => `page--${name}`,
  PAGE_HEADER: (name: string) => `page-header--${name}`,
  SIGN_IN_PAGE: "page-sign-in",
  PAGE_404: "page-404",
  PAGE_500: "page-500",
  PAGE_UNAUTHORIZED: "page-unauthorized",
  PAGE_ACCOUNT: "page--account",

  // Sign In
  SIGN_IN_WELCOME_HEADING: "sign-in-welcome-heading",
  SIGN_IN_SUBHEADING: "sign-in-subheading",
  SIGN_IN_FORM: "sign-in-form",
  SIGN_IN_EMAIL_INPUT: "sign-in-email-input",
  SIGN_IN_PASSWORD_INPUT: "sign-in-password-input",
  SIGN_IN_SUBMIT_BUTTON: "sign-in-submit-button",

  // Account
  ACCOUNT_AVATAR: "account-avatar",
  ACCOUNT_DISPLAY_NAME: "account-display-name",
  ACCOUNT_EMAIL: "account-email",
  ACCOUNT_EMAIL_VERIFICATION_STATUS: "account-email-verification-status",
  ACCOUNT_JOINED_DATE: "account-joined-date",
  ACCOUNT_LOCALE: "account-locale",
  ACCOUNT_PLATFORM_AUTHORITIES: "account-platform-authorities",
  ACCOUNT_PLATFORM_AUTHORITY: (authority: string) => `account-platform-authority--${authority}`,

  // Notifications
  NOTIFICATION: (type: string) => `notification--${type}`,
  NOTIFICATION_CONTAINER: "notifications-container",
  NOTIFICATION_BELL_BUTTON: "notification-bell-button",
  NOTIFICATION_BELL_DROPDOWN: "notification-bell-dropdown",
  NOTIFICATION_DELETE: (id: string) => `notification-delete-${id}`,
  NOTIFICATION_DELETE_ALL: "notification-delete-all",
  NOTIFICATION_ITEM: (id: string) => `notification-item-${id}`,
  NOTIFICATION_MARK_ALL_READ: "notification-mark-all-read",
  NOTIFICATION_SEE_ALL: "notification-see-all",

  // Badges
  BADGE: {
    ANNOUNCEMENT_LOCALE: (id: string, locale: string) =>
      `badge-announcement-locale--${id}--${locale}`,
    ANNOUNCEMENT_STATUS: (status: string) => `badge-announcement-status--${status}`,
    ANNOUNCEMENT_TYPE: (id: string) => `badge-announcement-type--${id}`,
    ANNOUNCEMENTS_TOTAL_COUNT: "badge-announcements-total-count",
    AUDIT_SEVERITY: (severity: string) => `badge-audit-severity--${severity}`,
    AUDIT_SEVERITY_RECORD: (severity: string) => `badge-audit-severity-${severity}`,
    AUDIT_TOTAL_COUNT: "badge-audit-total-count",
    EMAIL_VERIFIED: (userId: string) => `badge-email-verified--${userId}`,
    INVITATION_STATUS: (status: string) => `badge-invitation-status--${status}`,
    INVITATIONS_TOTAL_COUNT: "badge-invitations-total-count",
    LOCKED_USERS_ACTION_NEEDED: "badge-locked-users-action-needed",
    MEMBER_AUTHORITY: (userId: string, auth: string) =>
      `badge-member-authority--${userId}--${auth}`,
    MEMBER_EMAIL_VERIFIED: (userId: string) => `badge-member-email-verified--${userId}`,
    MEMBER_STATUS: (userId: string) => `badge-member-status--${userId}`,
    MEMBERS_TOTAL_COUNT: "badge-members-total-count",
    ORG_MEMBER_COUNT: "badge-org-member-count",
    ORG_REFUND_STATUS: (id: string) => `badge-org-refund-status--${id}`,
    ORG_REFUNDS_TOTAL_COUNT: "badge-org-refunds-total-count",
    ORG_SUB_STATUS: (id: string) => `badge-org-sub-status--${id}`,
    ORG_SUBS_TOTAL_COUNT: "badge-org-subs-total-count",
    ORG_SUBSCRIPTION_COUNT: "badge-org-subscription-count",
    ORGS_TAB_COUNT: "badge-orgs-tab-count",
    ORGS_TOTAL_COUNT: "badge-orgs-total-count",
    OVERVIEW_ORG_COUNT: "badge-overview-org-count",
    OVERVIEW_SUB_STATUS: (subId: string) => `badge-overview-sub-status--${subId}`,
    OVERVIEW_SUBSCRIPTION_COUNT: "badge-overview-subscription-count",
    PAST_DUE_SUBSCRIPTIONS_REVENUE_RISK: "badge-past-due-subscriptions-revenue-risk",
    PENDING_INVITATIONS_COUNT: "badge-pending-invitations-count",
    PLATFORM_ADMIN_STATUS: "badge-platform-admin-status",
    REFUND_DETAIL_STATUS: "badge-refund-detail-status",
    REFUND_STATUS: (status: string) => `badge-refund-status-${status}`,
    REFUND_STATUS_ID: (id: string) => `badge-refund-status--${id}`,
    REFUNDS_TOTAL_COUNT: "badge-refunds-total-count",
    SIGNIN_FAILURE_REASON: (reason: string) => `badge-signin-failure-reason--${reason}`,
    SIGNIN_RESULT: (result: string) => `badge-signin-result--${result}`,
    SUB_AUTO_RENEW: (subscriptionId: string) => `badge-sub-auto-renew--${subscriptionId}`,
    SUB_DETAIL_STATUS: "badge-sub-detail-status",
    SUB_STATUS: (subscriptionId: string) => `badge-sub-status--${subscriptionId}`,
    SUBS_TOTAL_COUNT: "badge-subs-total-count",
    SUSPENDED_ORG_STATUS: (tenantKey: string) => `badge-suspended-org-status-${tenantKey}`,
    USERS_TOTAL_COUNT: "badge-users-total-count",
  },

  // Menu Items
  MENU_ITEM: {
    BAN_USER: (userId: string) => `menu-item-ban-user--${userId}`,
    EDIT_USER: (userId: string) => `menu-item-edit-user--${userId}`,
    SET_PASSWORD: (userId: string) => `menu-item-set-password--${userId}`,
    SUB_CANCEL: (subscriptionId: string) => `menu-item-sub-cancel--${subscriptionId}`,
    SUB_PAUSE: (subscriptionId: string) => `menu-item-sub-pause--${subscriptionId}`,
    SUB_REACTIVATE: (subscriptionId: string) => `menu-item-sub-reactivate--${subscriptionId}`,
    SUB_UPDATE_QTY: (subscriptionId: string) => `menu-item-sub-update-qty--${subscriptionId}`,
    UNBAN_USER: (userId: string) => `menu-item-unban-user--${userId}`,
    UNLOCK_USER: (userId: string) => `menu-item-unlock-user--${userId}`,
  },

  // Stats
  STAT: {
    ACTIVE_SUBSCRIPTIONS: "stat-active-subscriptions",
    CARD_AUDIT_ACTION: (action: string) => `stat-card-audit-action--${action}`,
    CARD_SIGNIN_FAILED: "stat-card-signin-failed",
    CARD_SIGNIN_SUCCESS_RATE: "stat-card-signin-success-rate",
    CARD_SIGNIN_SUCCESSFUL: "stat-card-signin-successful",
    CARD_SIGNIN_TOTAL: "stat-card-signin-total",
    LOCKED_USERS: "stat-locked-users",
    ORG_CREATED_AT: "stat-org-created-at",
    ORG_MEMBER_COUNT: "stat-org-member-count",
    ORG_SUBSCRIPTION_COUNT: "stat-org-subscription-count",
    ORG_UPDATED_AT: "stat-org-updated-at",
    PAST_DUE_SUBSCRIPTIONS: "stat-past-due-subscriptions",
    PENDING_INVITATIONS: "stat-pending-invitations",
    SUSPENDED_USERS: "stat-suspended-users",
    TOTAL_ORGANIZATIONS: "stat-total-organizations",
    TOTAL_USERS: "stat-total-users",
    USER_EMAIL_VERIFIED: "stat-user-email-verified",
    USER_EMAIL_VERIFIED_BADGE: "stat-user-email-verified-badge",
    USER_JOINED_AT: "stat-user-joined-at",
    USER_ORG_COUNT: "stat-user-org-count",
    USER_UPDATED_AT: "stat-user-updated-at",
    VALUE_SIGNIN_FAILED: "stat-value-signin-failed",
    VALUE_SIGNIN_SUCCESS_RATE: "stat-value-signin-success-rate",
    VALUE_SIGNIN_SUCCESSFUL: "stat-value-signin-successful",
    VALUE_SIGNIN_TOTAL: "stat-value-signin-total",
  },

  // Tabs
  TAB: {
    AUDIT_ALL_EVENTS: "tab-audit-all-events",
    AUDIT_SIGNIN_ATTEMPTS: "tab-audit-signin-attempts",
    ORG_BILLING: "tab-org-billing",
    ORG_MEMBERS: "tab-org-members",
    ORG_OVERVIEW: "tab-org-overview",
    ORG_REFUNDS: "tab-org-refunds",
    ORG_SUBSCRIPTIONS: "tab-org-subscriptions",
    USER_ORGANIZATIONS: "tab-user-organizations",
    USER_OVERVIEW: "tab-user-overview",
    USER_PLATFORM_AUTHORITY: "tab-user-platform-authority",
  },

  // Selects
  SELECT: {
    ANNOUNCEMENTS_STATUS_FILTER: "select-announcements-status-filter",
    ANNOUNCEMENTS_TYPE_FILTER: "select-announcements-type-filter",
    AUDIT_ACTION_FILTER: "select-audit-action-filter",
    INVITATIONS_STATUS_FILTER: "select-invitations-status-filter",
    ORG_SUBS_STATUS_FILTER: "select-org-subs-status-filter",
    ORGS_STATUS_FILTER: "select-orgs-status-filter",
    SUBS_STATUS_FILTER: "select-subs-status-filter",
    USERS_STATUS_FILTER: "select-users-status-filter",
  },

  // Org Detail
  ORG_DETAIL_HERO_CARD: "org-detail-hero-card",
  ORG_DETAIL_ICON: "org-detail-icon",
  ORG_DETAIL_NAME: "org-detail-name",
  ORG_DETAIL_TENANT_KEY: "org-detail-tenant-key",
  ORG_DETAIL_CREATED_AT: "org-detail-created-at",
  ORG_DETAIL_MEMBER_COUNT: "org-detail-member-count",
  ORG_DETAIL_SUBSCRIPTION_COUNT: "org-detail-subscription-count",

  // User Detail
  USER_DETAIL_HERO_CARD: "user-detail-hero-card",
  USER_DETAIL_AVATAR: "user-detail-avatar",
  USER_DETAIL_DISPLAY_NAME: "user-detail-display-name",
  USER_DETAIL_EMAIL: "user-detail-email",
  USER_DETAIL_EMAIL_VERIFIED_BADGE: "user-detail-email-verified-badge",
  USER_DETAIL_JOINED_AT: "user-detail-joined-at",
  USER_DETAIL_ORG_COUNT: "user-detail-org-count",
  USER_STATUS_BADGE: (status: string) => `user-status-badge--${status}`,
} as const;

/**
 * Helper function to create data-testid attribute
 */
export const testId = (value: string): { "data-testid": string } => ({
  "data-testid": value,
});

/**
 * Helper function to create test selector for Playwright
 */
export const byTestId = (value: string): string => `[data-testid="${value}"]`;
