/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root"
import { Route as UnauthorizedRouteImport } from "./pages/unauthorized"
import { Route as SignInRouteImport } from "./pages/sign-in"
import { Route as LoadingDemoRouteImport } from "./pages/loading-demo"
import { Route as AdminRouteImport } from "./pages/admin"
import { Route as R500RouteImport } from "./pages/500"
import { Route as R404RouteImport } from "./pages/404"
import { Route as IndexRouteImport } from "./pages/index"
import { Route as AdminIndexRouteImport } from "./pages/admin/index"
import { Route as AdminUsersRouteImport } from "./pages/admin/users"
import { Route as AdminSubscriptionsRouteImport } from "./pages/admin/subscriptions"
import { Route as AdminRefundsRouteImport } from "./pages/admin/refunds"
import { Route as AdminPlansRouteImport } from "./pages/admin/plans"
import { Route as AdminOrganizationsRouteImport } from "./pages/admin/organizations"
import { Route as AdminInvitationsRouteImport } from "./pages/admin/invitations"
import { Route as AdminAnnouncementsRouteImport } from "./pages/admin/announcements"
import { Route as AdminAccountRouteImport } from "./pages/admin/account"
import { Route as AdminUsersIndexRouteImport } from "./pages/admin/users.index"
import { Route as AdminPlansIndexRouteImport } from "./pages/admin/plans.index"
import { Route as AdminOrganizationsIndexRouteImport } from "./pages/admin/organizations.index"
import { Route as AdminInvitationsIndexRouteImport } from "./pages/admin/invitations.index"
import { Route as AdminAnnouncementsIndexRouteImport } from "./pages/admin/announcements.index"
import { Route as AdminUsersUserIdRouteImport } from "./pages/admin/users.$userId"
import { Route as AdminSubscriptionsSubscriptionIdRouteImport } from "./pages/admin/subscriptions.$subscriptionId"
import { Route as AdminRefundsRefundIdRouteImport } from "./pages/admin/refunds.$refundId"
import { Route as AdminPlansPlanCodeRouteImport } from "./pages/admin/plans.$planCode"
import { Route as AdminOrganizationsTenantKeyRouteImport } from "./pages/admin/organizations.$tenantKey"
import { Route as AdminOrganizationsTenantKeyIndexRouteImport } from "./pages/admin/organizations.$tenantKey.index"
import { Route as AdminOrganizationsTenantKeySubscriptionsRouteImport } from "./pages/admin/organizations.$tenantKey.subscriptions"
import { Route as AdminOrganizationsTenantKeyRefundsRouteImport } from "./pages/admin/organizations.$tenantKey.refunds"
import { Route as AdminOrganizationsTenantKeyMembersRouteImport } from "./pages/admin/organizations.$tenantKey.members"
import { Route as AdminOrganizationsTenantKeyBillingRouteImport } from "./pages/admin/organizations.$tenantKey.billing"

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: "/unauthorized",
  path: "/unauthorized",
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any)
const LoadingDemoRoute = LoadingDemoRouteImport.update({
  id: "/loading-demo",
  path: "/loading-demo",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: "/500",
  path: "/500",
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: "/404",
  path: "/404",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: "/subscriptions",
  path: "/subscriptions",
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: "/refunds",
  path: "/refunds",
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvitationsRoute = AdminInvitationsRouteImport.update({
  id: "/invitations",
  path: "/invitations",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: "/announcements",
  path: "/announcements",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminPlansRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AdminInvitationsIndexRoute = AdminInvitationsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminInvitationsRoute,
} as any)
const AdminAnnouncementsIndexRoute = AdminAnnouncementsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminAnnouncementsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: "/$userId",
  path: "/$userId",
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSubscriptionsSubscriptionIdRoute =
  AdminSubscriptionsSubscriptionIdRouteImport.update({
    id: "/$subscriptionId",
    path: "/$subscriptionId",
    getParentRoute: () => AdminSubscriptionsRoute,
  } as any)
const AdminRefundsRefundIdRoute = AdminRefundsRefundIdRouteImport.update({
  id: "/$refundId",
  path: "/$refundId",
  getParentRoute: () => AdminRefundsRoute,
} as any)
const AdminPlansPlanCodeRoute = AdminPlansPlanCodeRouteImport.update({
  id: "/$planCode",
  path: "/$planCode",
  getParentRoute: () => AdminPlansRoute,
} as any)
const AdminOrganizationsTenantKeyRoute =
  AdminOrganizationsTenantKeyRouteImport.update({
    id: "/$tenantKey",
    path: "/$tenantKey",
    getParentRoute: () => AdminOrganizationsRoute,
  } as any)
const AdminOrganizationsTenantKeyIndexRoute =
  AdminOrganizationsTenantKeyIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AdminOrganizationsTenantKeyRoute,
  } as any)
const AdminOrganizationsTenantKeySubscriptionsRoute =
  AdminOrganizationsTenantKeySubscriptionsRouteImport.update({
    id: "/subscriptions",
    path: "/subscriptions",
    getParentRoute: () => AdminOrganizationsTenantKeyRoute,
  } as any)
const AdminOrganizationsTenantKeyRefundsRoute =
  AdminOrganizationsTenantKeyRefundsRouteImport.update({
    id: "/refunds",
    path: "/refunds",
    getParentRoute: () => AdminOrganizationsTenantKeyRoute,
  } as any)
const AdminOrganizationsTenantKeyMembersRoute =
  AdminOrganizationsTenantKeyMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => AdminOrganizationsTenantKeyRoute,
  } as any)
const AdminOrganizationsTenantKeyBillingRoute =
  AdminOrganizationsTenantKeyBillingRouteImport.update({
    id: "/billing",
    path: "/billing",
    getParentRoute: () => AdminOrganizationsTenantKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/admin": typeof AdminRouteWithChildren
  "/loading-demo": typeof LoadingDemoRoute
  "/sign-in": typeof SignInRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/admin/account": typeof AdminAccountRoute
  "/admin/announcements": typeof AdminAnnouncementsRouteWithChildren
  "/admin/invitations": typeof AdminInvitationsRouteWithChildren
  "/admin/organizations": typeof AdminOrganizationsRouteWithChildren
  "/admin/plans": typeof AdminPlansRouteWithChildren
  "/admin/refunds": typeof AdminRefundsRouteWithChildren
  "/admin/subscriptions": typeof AdminSubscriptionsRouteWithChildren
  "/admin/users": typeof AdminUsersRouteWithChildren
  "/admin/": typeof AdminIndexRoute
  "/admin/organizations/$tenantKey": typeof AdminOrganizationsTenantKeyRouteWithChildren
  "/admin/plans/$planCode": typeof AdminPlansPlanCodeRoute
  "/admin/refunds/$refundId": typeof AdminRefundsRefundIdRoute
  "/admin/subscriptions/$subscriptionId": typeof AdminSubscriptionsSubscriptionIdRoute
  "/admin/users/$userId": typeof AdminUsersUserIdRoute
  "/admin/announcements/": typeof AdminAnnouncementsIndexRoute
  "/admin/invitations/": typeof AdminInvitationsIndexRoute
  "/admin/organizations/": typeof AdminOrganizationsIndexRoute
  "/admin/plans/": typeof AdminPlansIndexRoute
  "/admin/users/": typeof AdminUsersIndexRoute
  "/admin/organizations/$tenantKey/billing": typeof AdminOrganizationsTenantKeyBillingRoute
  "/admin/organizations/$tenantKey/members": typeof AdminOrganizationsTenantKeyMembersRoute
  "/admin/organizations/$tenantKey/refunds": typeof AdminOrganizationsTenantKeyRefundsRoute
  "/admin/organizations/$tenantKey/subscriptions": typeof AdminOrganizationsTenantKeySubscriptionsRoute
  "/admin/organizations/$tenantKey/": typeof AdminOrganizationsTenantKeyIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/loading-demo": typeof LoadingDemoRoute
  "/sign-in": typeof SignInRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/admin/account": typeof AdminAccountRoute
  "/admin/refunds": typeof AdminRefundsRouteWithChildren
  "/admin/subscriptions": typeof AdminSubscriptionsRouteWithChildren
  "/admin": typeof AdminIndexRoute
  "/admin/plans/$planCode": typeof AdminPlansPlanCodeRoute
  "/admin/refunds/$refundId": typeof AdminRefundsRefundIdRoute
  "/admin/subscriptions/$subscriptionId": typeof AdminSubscriptionsSubscriptionIdRoute
  "/admin/users/$userId": typeof AdminUsersUserIdRoute
  "/admin/announcements": typeof AdminAnnouncementsIndexRoute
  "/admin/invitations": typeof AdminInvitationsIndexRoute
  "/admin/organizations": typeof AdminOrganizationsIndexRoute
  "/admin/plans": typeof AdminPlansIndexRoute
  "/admin/users": typeof AdminUsersIndexRoute
  "/admin/organizations/$tenantKey/billing": typeof AdminOrganizationsTenantKeyBillingRoute
  "/admin/organizations/$tenantKey/members": typeof AdminOrganizationsTenantKeyMembersRoute
  "/admin/organizations/$tenantKey/refunds": typeof AdminOrganizationsTenantKeyRefundsRoute
  "/admin/organizations/$tenantKey/subscriptions": typeof AdminOrganizationsTenantKeySubscriptionsRoute
  "/admin/organizations/$tenantKey": typeof AdminOrganizationsTenantKeyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/404": typeof R404Route
  "/500": typeof R500Route
  "/admin": typeof AdminRouteWithChildren
  "/loading-demo": typeof LoadingDemoRoute
  "/sign-in": typeof SignInRoute
  "/unauthorized": typeof UnauthorizedRoute
  "/admin/account": typeof AdminAccountRoute
  "/admin/announcements": typeof AdminAnnouncementsRouteWithChildren
  "/admin/invitations": typeof AdminInvitationsRouteWithChildren
  "/admin/organizations": typeof AdminOrganizationsRouteWithChildren
  "/admin/plans": typeof AdminPlansRouteWithChildren
  "/admin/refunds": typeof AdminRefundsRouteWithChildren
  "/admin/subscriptions": typeof AdminSubscriptionsRouteWithChildren
  "/admin/users": typeof AdminUsersRouteWithChildren
  "/admin/": typeof AdminIndexRoute
  "/admin/organizations/$tenantKey": typeof AdminOrganizationsTenantKeyRouteWithChildren
  "/admin/plans/$planCode": typeof AdminPlansPlanCodeRoute
  "/admin/refunds/$refundId": typeof AdminRefundsRefundIdRoute
  "/admin/subscriptions/$subscriptionId": typeof AdminSubscriptionsSubscriptionIdRoute
  "/admin/users/$userId": typeof AdminUsersUserIdRoute
  "/admin/announcements/": typeof AdminAnnouncementsIndexRoute
  "/admin/invitations/": typeof AdminInvitationsIndexRoute
  "/admin/organizations/": typeof AdminOrganizationsIndexRoute
  "/admin/plans/": typeof AdminPlansIndexRoute
  "/admin/users/": typeof AdminUsersIndexRoute
  "/admin/organizations/$tenantKey/billing": typeof AdminOrganizationsTenantKeyBillingRoute
  "/admin/organizations/$tenantKey/members": typeof AdminOrganizationsTenantKeyMembersRoute
  "/admin/organizations/$tenantKey/refunds": typeof AdminOrganizationsTenantKeyRefundsRoute
  "/admin/organizations/$tenantKey/subscriptions": typeof AdminOrganizationsTenantKeySubscriptionsRoute
  "/admin/organizations/$tenantKey/": typeof AdminOrganizationsTenantKeyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/404"
    | "/500"
    | "/admin"
    | "/loading-demo"
    | "/sign-in"
    | "/unauthorized"
    | "/admin/account"
    | "/admin/announcements"
    | "/admin/invitations"
    | "/admin/organizations"
    | "/admin/plans"
    | "/admin/refunds"
    | "/admin/subscriptions"
    | "/admin/users"
    | "/admin/"
    | "/admin/organizations/$tenantKey"
    | "/admin/plans/$planCode"
    | "/admin/refunds/$refundId"
    | "/admin/subscriptions/$subscriptionId"
    | "/admin/users/$userId"
    | "/admin/announcements/"
    | "/admin/invitations/"
    | "/admin/organizations/"
    | "/admin/plans/"
    | "/admin/users/"
    | "/admin/organizations/$tenantKey/billing"
    | "/admin/organizations/$tenantKey/members"
    | "/admin/organizations/$tenantKey/refunds"
    | "/admin/organizations/$tenantKey/subscriptions"
    | "/admin/organizations/$tenantKey/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/404"
    | "/500"
    | "/loading-demo"
    | "/sign-in"
    | "/unauthorized"
    | "/admin/account"
    | "/admin/refunds"
    | "/admin/subscriptions"
    | "/admin"
    | "/admin/plans/$planCode"
    | "/admin/refunds/$refundId"
    | "/admin/subscriptions/$subscriptionId"
    | "/admin/users/$userId"
    | "/admin/announcements"
    | "/admin/invitations"
    | "/admin/organizations"
    | "/admin/plans"
    | "/admin/users"
    | "/admin/organizations/$tenantKey/billing"
    | "/admin/organizations/$tenantKey/members"
    | "/admin/organizations/$tenantKey/refunds"
    | "/admin/organizations/$tenantKey/subscriptions"
    | "/admin/organizations/$tenantKey"
  id:
    | "__root__"
    | "/"
    | "/404"
    | "/500"
    | "/admin"
    | "/loading-demo"
    | "/sign-in"
    | "/unauthorized"
    | "/admin/account"
    | "/admin/announcements"
    | "/admin/invitations"
    | "/admin/organizations"
    | "/admin/plans"
    | "/admin/refunds"
    | "/admin/subscriptions"
    | "/admin/users"
    | "/admin/"
    | "/admin/organizations/$tenantKey"
    | "/admin/plans/$planCode"
    | "/admin/refunds/$refundId"
    | "/admin/subscriptions/$subscriptionId"
    | "/admin/users/$userId"
    | "/admin/announcements/"
    | "/admin/invitations/"
    | "/admin/organizations/"
    | "/admin/plans/"
    | "/admin/users/"
    | "/admin/organizations/$tenantKey/billing"
    | "/admin/organizations/$tenantKey/members"
    | "/admin/organizations/$tenantKey/refunds"
    | "/admin/organizations/$tenantKey/subscriptions"
    | "/admin/organizations/$tenantKey/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AdminRoute: typeof AdminRouteWithChildren
  LoadingDemoRoute: typeof LoadingDemoRoute
  SignInRoute: typeof SignInRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/unauthorized": {
      id: "/unauthorized"
      path: "/unauthorized"
      fullPath: "/unauthorized"
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/loading-demo": {
      id: "/loading-demo"
      path: "/loading-demo"
      fullPath: "/loading-demo"
      preLoaderRoute: typeof LoadingDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/500": {
      id: "/500"
      path: "/500"
      fullPath: "/500"
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/404": {
      id: "/404"
      path: "/404"
      fullPath: "/404"
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/subscriptions": {
      id: "/admin/subscriptions"
      path: "/subscriptions"
      fullPath: "/admin/subscriptions"
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/refunds": {
      id: "/admin/refunds"
      path: "/refunds"
      fullPath: "/admin/refunds"
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/plans": {
      id: "/admin/plans"
      path: "/plans"
      fullPath: "/admin/plans"
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/organizations": {
      id: "/admin/organizations"
      path: "/organizations"
      fullPath: "/admin/organizations"
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/invitations": {
      id: "/admin/invitations"
      path: "/invitations"
      fullPath: "/admin/invitations"
      preLoaderRoute: typeof AdminInvitationsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/announcements": {
      id: "/admin/announcements"
      path: "/announcements"
      fullPath: "/admin/announcements"
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/account": {
      id: "/admin/account"
      path: "/account"
      fullPath: "/admin/account"
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/users/": {
      id: "/admin/users/"
      path: "/"
      fullPath: "/admin/users/"
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    "/admin/plans/": {
      id: "/admin/plans/"
      path: "/"
      fullPath: "/admin/plans/"
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminPlansRoute
    }
    "/admin/organizations/": {
      id: "/admin/organizations/"
      path: "/"
      fullPath: "/admin/organizations/"
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    "/admin/invitations/": {
      id: "/admin/invitations/"
      path: "/"
      fullPath: "/admin/invitations/"
      preLoaderRoute: typeof AdminInvitationsIndexRouteImport
      parentRoute: typeof AdminInvitationsRoute
    }
    "/admin/announcements/": {
      id: "/admin/announcements/"
      path: "/"
      fullPath: "/admin/announcements/"
      preLoaderRoute: typeof AdminAnnouncementsIndexRouteImport
      parentRoute: typeof AdminAnnouncementsRoute
    }
    "/admin/users/$userId": {
      id: "/admin/users/$userId"
      path: "/$userId"
      fullPath: "/admin/users/$userId"
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    "/admin/subscriptions/$subscriptionId": {
      id: "/admin/subscriptions/$subscriptionId"
      path: "/$subscriptionId"
      fullPath: "/admin/subscriptions/$subscriptionId"
      preLoaderRoute: typeof AdminSubscriptionsSubscriptionIdRouteImport
      parentRoute: typeof AdminSubscriptionsRoute
    }
    "/admin/refunds/$refundId": {
      id: "/admin/refunds/$refundId"
      path: "/$refundId"
      fullPath: "/admin/refunds/$refundId"
      preLoaderRoute: typeof AdminRefundsRefundIdRouteImport
      parentRoute: typeof AdminRefundsRoute
    }
    "/admin/plans/$planCode": {
      id: "/admin/plans/$planCode"
      path: "/$planCode"
      fullPath: "/admin/plans/$planCode"
      preLoaderRoute: typeof AdminPlansPlanCodeRouteImport
      parentRoute: typeof AdminPlansRoute
    }
    "/admin/organizations/$tenantKey": {
      id: "/admin/organizations/$tenantKey"
      path: "/$tenantKey"
      fullPath: "/admin/organizations/$tenantKey"
      preLoaderRoute: typeof AdminOrganizationsTenantKeyRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    "/admin/organizations/$tenantKey/": {
      id: "/admin/organizations/$tenantKey/"
      path: "/"
      fullPath: "/admin/organizations/$tenantKey/"
      preLoaderRoute: typeof AdminOrganizationsTenantKeyIndexRouteImport
      parentRoute: typeof AdminOrganizationsTenantKeyRoute
    }
    "/admin/organizations/$tenantKey/subscriptions": {
      id: "/admin/organizations/$tenantKey/subscriptions"
      path: "/subscriptions"
      fullPath: "/admin/organizations/$tenantKey/subscriptions"
      preLoaderRoute: typeof AdminOrganizationsTenantKeySubscriptionsRouteImport
      parentRoute: typeof AdminOrganizationsTenantKeyRoute
    }
    "/admin/organizations/$tenantKey/refunds": {
      id: "/admin/organizations/$tenantKey/refunds"
      path: "/refunds"
      fullPath: "/admin/organizations/$tenantKey/refunds"
      preLoaderRoute: typeof AdminOrganizationsTenantKeyRefundsRouteImport
      parentRoute: typeof AdminOrganizationsTenantKeyRoute
    }
    "/admin/organizations/$tenantKey/members": {
      id: "/admin/organizations/$tenantKey/members"
      path: "/members"
      fullPath: "/admin/organizations/$tenantKey/members"
      preLoaderRoute: typeof AdminOrganizationsTenantKeyMembersRouteImport
      parentRoute: typeof AdminOrganizationsTenantKeyRoute
    }
    "/admin/organizations/$tenantKey/billing": {
      id: "/admin/organizations/$tenantKey/billing"
      path: "/billing"
      fullPath: "/admin/organizations/$tenantKey/billing"
      preLoaderRoute: typeof AdminOrganizationsTenantKeyBillingRouteImport
      parentRoute: typeof AdminOrganizationsTenantKeyRoute
    }
  }
}

interface AdminAnnouncementsRouteChildren {
  AdminAnnouncementsIndexRoute: typeof AdminAnnouncementsIndexRoute
}

const AdminAnnouncementsRouteChildren: AdminAnnouncementsRouteChildren = {
  AdminAnnouncementsIndexRoute: AdminAnnouncementsIndexRoute,
}

const AdminAnnouncementsRouteWithChildren =
  AdminAnnouncementsRoute._addFileChildren(AdminAnnouncementsRouteChildren)

interface AdminInvitationsRouteChildren {
  AdminInvitationsIndexRoute: typeof AdminInvitationsIndexRoute
}

const AdminInvitationsRouteChildren: AdminInvitationsRouteChildren = {
  AdminInvitationsIndexRoute: AdminInvitationsIndexRoute,
}

const AdminInvitationsRouteWithChildren =
  AdminInvitationsRoute._addFileChildren(AdminInvitationsRouteChildren)

interface AdminOrganizationsTenantKeyRouteChildren {
  AdminOrganizationsTenantKeyBillingRoute: typeof AdminOrganizationsTenantKeyBillingRoute
  AdminOrganizationsTenantKeyMembersRoute: typeof AdminOrganizationsTenantKeyMembersRoute
  AdminOrganizationsTenantKeyRefundsRoute: typeof AdminOrganizationsTenantKeyRefundsRoute
  AdminOrganizationsTenantKeySubscriptionsRoute: typeof AdminOrganizationsTenantKeySubscriptionsRoute
  AdminOrganizationsTenantKeyIndexRoute: typeof AdminOrganizationsTenantKeyIndexRoute
}

const AdminOrganizationsTenantKeyRouteChildren: AdminOrganizationsTenantKeyRouteChildren =
  {
    AdminOrganizationsTenantKeyBillingRoute:
      AdminOrganizationsTenantKeyBillingRoute,
    AdminOrganizationsTenantKeyMembersRoute:
      AdminOrganizationsTenantKeyMembersRoute,
    AdminOrganizationsTenantKeyRefundsRoute:
      AdminOrganizationsTenantKeyRefundsRoute,
    AdminOrganizationsTenantKeySubscriptionsRoute:
      AdminOrganizationsTenantKeySubscriptionsRoute,
    AdminOrganizationsTenantKeyIndexRoute:
      AdminOrganizationsTenantKeyIndexRoute,
  }

const AdminOrganizationsTenantKeyRouteWithChildren =
  AdminOrganizationsTenantKeyRoute._addFileChildren(
    AdminOrganizationsTenantKeyRouteChildren,
  )

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsTenantKeyRoute: typeof AdminOrganizationsTenantKeyRouteWithChildren
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsTenantKeyRoute:
    AdminOrganizationsTenantKeyRouteWithChildren,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminPlansRouteChildren {
  AdminPlansPlanCodeRoute: typeof AdminPlansPlanCodeRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
}

const AdminPlansRouteChildren: AdminPlansRouteChildren = {
  AdminPlansPlanCodeRoute: AdminPlansPlanCodeRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
}

const AdminPlansRouteWithChildren = AdminPlansRoute._addFileChildren(
  AdminPlansRouteChildren,
)

interface AdminRefundsRouteChildren {
  AdminRefundsRefundIdRoute: typeof AdminRefundsRefundIdRoute
}

const AdminRefundsRouteChildren: AdminRefundsRouteChildren = {
  AdminRefundsRefundIdRoute: AdminRefundsRefundIdRoute,
}

const AdminRefundsRouteWithChildren = AdminRefundsRoute._addFileChildren(
  AdminRefundsRouteChildren,
)

interface AdminSubscriptionsRouteChildren {
  AdminSubscriptionsSubscriptionIdRoute: typeof AdminSubscriptionsSubscriptionIdRoute
}

const AdminSubscriptionsRouteChildren: AdminSubscriptionsRouteChildren = {
  AdminSubscriptionsSubscriptionIdRoute: AdminSubscriptionsSubscriptionIdRoute,
}

const AdminSubscriptionsRouteWithChildren =
  AdminSubscriptionsRoute._addFileChildren(AdminSubscriptionsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRouteWithChildren
  AdminInvitationsRoute: typeof AdminInvitationsRouteWithChildren
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminPlansRoute: typeof AdminPlansRouteWithChildren
  AdminRefundsRoute: typeof AdminRefundsRouteWithChildren
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRouteWithChildren,
  AdminInvitationsRoute: AdminInvitationsRouteWithChildren,
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminPlansRoute: AdminPlansRouteWithChildren,
  AdminRefundsRoute: AdminRefundsRouteWithChildren,
  AdminSubscriptionsRoute: AdminSubscriptionsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  R500Route: R500Route,
  AdminRoute: AdminRouteWithChildren,
  LoadingDemoRoute: LoadingDemoRoute,
  SignInRoute: SignInRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
